# Generated by Django 5.2.14 on 2026-05-14 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=100)),
                ('first_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('weakness_tags', models.TextField(blank=True)),
                ('better_answer', models.TextField(blank=True)),
                ('next_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interviewsession')),
            ],
        ),
    ]
