# Generated by Django 5.2.14 on 2026-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_queation',
            field=models.TextField(blank=True),
        ),
    ]
