# Generated by Django 5.2.14 on 2026-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interviewsession_current_queation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='current_queation',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_question',
            field=models.TextField(blank=True),
        ),
    ]
