# Generated by Django 5.2.14 on 2026-05-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_interviewsession_current_queation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDefenseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('technologies', models.TextField()),
                ('target_role', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('current_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDefenseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('weakness_tags', models.TextField(blank=True)),
                ('better_answer', models.TextField(blank=True)),
                ('next_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectdefensesession')),
            ],
        ),
    ]
